#include "../kernel/gui/window.h"
#include "../kernel/gui/widgets.h"
#include "../kernel/config/sys_env.h"
#include "../kernel/net/supabase_client.h"
#include "../kernel/db/local_db.h"

static Window *w; static Button *cat_sys,*cat_disp,*cat_net,*cat_user,*apply,*fps30,*fps60,*theme_b,*theme_g; static TextBox *ip,*sub,*gw,*url,*key,*user,*pass; static int tab=0;
static void set(TextBox*t,const char*s){t->buffer_index=0; for(int i=0;s[i]&&i<255;i++) t->text_buffer[t->buffer_index++]=s[i]; t->text_buffer[t->buffer_index]=0;}
static void do_apply(void){ sys_env_set_supabase(url->text_buffer,key->text_buffer); supabase_init(url->text_buffer,key->text_buffer); db_open("USERS.DB"); char q[256]="INSERT INTO users VALUES ("; int p=25; for(int i=0;user->text_buffer[i]&&p<240;i++)q[p++]=user->text_buffer[i]; q[p++]=','; for(int i=0;pass->text_buffer[i]&&p<250;i++)q[p++]=pass->text_buffer[i]; q[p++]=')'; q[p]=0; char o[64]; db_query(q,o,64); }
void control_panel_open(void){ w=window_create("Denetim Masasi",180,70,640,440,1); cat_sys=button_create(10,40,120,26,"Sistem",0); cat_disp=button_create(10,72,120,26,"Ekran",0); cat_net=button_create(10,104,120,26,"Ag",0); cat_user=button_create(10,136,120,26,"Kullanicilar",0); apply=button_create(500,390,120,28,"Uygula",do_apply); fps30=button_create(160,240,70,24,"30 FPS",0); fps60=button_create(240,240,70,24,"60 FPS",0); theme_b=button_create(160,270,90,24,"Mavi",0); theme_g=button_create(260,270,90,24,"Yesil",0); ip=textbox_create(160,80,180,24); sub=textbox_create(160,112,180,24); gw=textbox_create(160,144,180,24); url=textbox_create(160,176,320,24); key=textbox_create(160,208,320,24); user=textbox_create(160,304,180,24); pass=textbox_create(350,304,180,24); set(ip,"10.0.2.15"); set(sub,"255.255.255.0"); set(gw,"10.0.2.2"); set(url,g_syscfg.supabase_url); set(key,g_syscfg.supabase_key); set(user,g_syscfg.active_user); set(pass,"1234"); }
void control_panel_draw(void){ if(!w) return; widget_draw_button(cat_sys,w->x,w->y); widget_draw_button(cat_disp,w->x,w->y); widget_draw_button(cat_net,w->x,w->y); widget_draw_button(cat_user,w->x,w->y); widget_draw_textbox(ip,w->x,w->y); widget_draw_textbox(sub,w->x,w->y); widget_draw_textbox(gw,w->x,w->y); widget_draw_textbox(url,w->x,w->y); widget_draw_textbox(key,w->x,w->y); widget_draw_textbox(user,w->x,w->y); widget_draw_textbox(pass,w->x,w->y); widget_draw_button(fps30,w->x,w->y); widget_draw_button(fps60,w->x,w->y); widget_draw_button(theme_b,w->x,w->y); widget_draw_button(theme_g,w->x,w->y); widget_draw_button(apply,w->x,w->y);} 
void control_panel_click(int mx,int my){ if(!w) return; if(widget_button_hit(cat_sys,mx,my,w->x,w->y))tab=0; if(widget_button_hit(cat_disp,mx,my,w->x,w->y))tab=1; if(widget_button_hit(cat_net,mx,my,w->x,w->y))tab=2; if(widget_button_hit(cat_user,mx,my,w->x,w->y))tab=3; if(widget_button_hit(fps30,mx,my,w->x,w->y))sys_env_set_fps(30); if(widget_button_hit(fps60,mx,my,w->x,w->y))sys_env_set_fps(60); if(widget_button_hit(theme_b,mx,my,w->x,w->y))sys_env_set_theme(0x00245EDD); if(widget_button_hit(theme_g,mx,my,w->x,w->y))sys_env_set_theme(0x00388E3C); if(widget_button_hit(apply,mx,my,w->x,w->y)&&apply->on_click)apply->on_click(); ip->is_focused=widget_textbox_hit(ip,mx,my,w->x,w->y); sub->is_focused=widget_textbox_hit(sub,mx,my,w->x,w->y); gw->is_focused=widget_textbox_hit(gw,mx,my,w->x,w->y); url->is_focused=widget_textbox_hit(url,mx,my,w->x,w->y); key->is_focused=widget_textbox_hit(key,mx,my,w->x,w->y); user->is_focused=widget_textbox_hit(user,mx,my,w->x,w->y); pass->is_focused=widget_textbox_hit(pass,mx,my,w->x,w->y); }
void control_panel_key(char c){ if(ip->is_focused)widget_textbox_input(ip,c); if(sub->is_focused)widget_textbox_input(sub,c); if(gw->is_focused)widget_textbox_input(gw,c); if(url->is_focused)widget_textbox_input(url,c); if(key->is_focused)widget_textbox_input(key,c); if(user->is_focused)widget_textbox_input(user,c); if(pass->is_focused)widget_textbox_input(pass,c); }
